version: '3.8'

services:

  # https://github.com/nacos-group/nacos-docker
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      TZ: Asia/Shanghai
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
        # MYSQL_SERVICE_HOST: internet_ip
        # intranet_ip:
      MYSQL_SERVICE_HOST: 172.16.0.16 
      MYSQL_SERVICE_PORT: 3309
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    volumes:
      # log
      - /docker/spring-cloud/nacos/logs/:/home/nacos/logs
        # - ./config/nacos-logback.xml:/home/nacos/conf/nacos-logback.xml
        # - ./config/application.properties:/home/nacos/conf/application.properties
    privileged: true
