version: '3.8'

services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - 8000:9000
    volumes:
      - /docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

